apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: giu3y9s70-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: giu3y9s70-go 
  name: giu3y9s70-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: giu3y9s70-go 
